server:
  port: 403
spring:
  application:
    name: auth-control
  profiles:
    active: dev
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
  global-config:
    db-config:
      logic-delete-field: del
      logic-delete-value: true
      logic-not-delete-value: false
      id-type: assign_id
logging:
  level:
    com.cmzn.authcontrol: debug